# Mini batch Gradient descent

in Mini batch Gradient descent we update values of coefficent no of batch times in an epoch

by making no of batch=1 we can achive SGD

by making no of batch=n we can achive GD

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_regression
import random

In [2]:
X,y=make_regression(n_samples=100,n_features=3,n_informative=1,n_targets=1,noise=20)

In [3]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr=LinearRegression()
lr.fit(X_train,y_train)
print(lr.coef_,lr.intercept_)
y_pred=lr.predict(X_test)
print("r2 score " , r2_score(y_test,y_pred))

[92.99518725 -1.02634273 -2.08077038] 0.7242613081460902
r2 score  0.9072804404080195


In [25]:
class MBGD:
    def __init__(self,epochs,lr,batchsize):
        self.epochs=epochs
        self.lr=lr
        self.batchsize=batchsize
        
    def fit(self,X,y):
        
        X=np.insert(X,0,1,axis=1)
        
        self.b=np.ones(X.shape[1])
        
        for p in range(self.epochs):
            for i in range(len(X)//self.batchsize):
                idx=random.sample(range(len(X)),self.batchsize)
                X=X[idx]
                y=y[idx]
                y_pred=X @ self.b
                error = y - y_pred 
                gradient=-2 * X.T @ error / len(X)
                self.b=self.b - gradient * self.lr
        
        print(self.b)

    def predict(self,X):
        X=np.insert(X,0,1,axis=1)

        ans=X@self.b

        return ans

In [36]:
gd=MBGD(40,0.1,20)
gd.fit(X_train,y_train)
y_pred=gd.predict(X_test)
y_pred

[-0.26429485 91.57101695 -0.20696985  1.77021041]


array([-53.80676191, -67.03777344, -90.39683318, 110.14097659,
        69.51356   , -26.34943908, -22.43754753, 125.08554418,
        -1.80021566,  -1.29247928])

In [37]:
print("r2 score " , r2_score(y_test,y_pred))

r2 score  0.917176614985003


# Problems with SGD

1- it does not decrease steps when move toward solution so we do as in previous notebook known as learning shedule

# sckit learn implementation

In [40]:
from sklearn.linear_model import SGDRegressor

mbdg=SGDRegressor(eta0=0.01,learning_rate='constant')


In [41]:
epochs=100
batchsize=10
for i in range(epochs):
    idx=random.sample(range(len(X)),batchsize)
    mbdg.partial_fit(X[idx],y[idx])  #partial_fit fit that only one time

In [42]:
y_pred=mbdg.predict(X_test)
print("r2 score " , r2_score(y_test,y_pred))

r2 score  0.9017055388433269
